## 2024-12-17

#### 조건문표현식, 리스트 컴프리헨션

In [7]:
score=int(input('점수'))
message="success" if score>=60 else"failure"
print(message)

success


In [10]:
squares=[1,2,3,4,5]
numbers=list(range(1,11))
for x in numbers:
    squares.append(x**2)
print(squares)

[1, 2, 3, 4, 5, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [8]:
numbers=[1,2,3,4,5]
squares=[x**2 for x in numbers]
print(squares)

[1, 4, 9, 16, 25]


In [13]:
numbers=[1,2,3,4,5,6,7]
even_numbers=[x for x in numbers if x %2==0]
print(even_numbers)

[2, 4, 6]


In [14]:
numbers=[1,2,3,4,5,6,7]
even_pownumbers=[x**2 for x in numbers if x %2==0]
print(even_pownumbers)

[4, 16, 36]


#### NumPy

In [16]:
pip install numpy


   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------- ----------------------------- 3.4/12.6 MB 18.4 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.6 MB 18.8 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 20.4 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 19.3 MB/s eta 0:00:00


In [17]:
import numpy as np

In [18]:
np.__version__

'2.2.1'

In [23]:
a_list=[1,2,3,4]
a_list

[1, 2, 3, 4]

In [22]:
type(a_list)

list

In [24]:
int_arr=np.array([1,2,3,4])
int_arr

array([1, 2, 3, 4])

In [25]:
print(int_arr)

[1 2 3 4]


In [26]:
type(int_arr)

numpy.ndarray

In [ ]:
list_data=[1,2.2,'3',[1,2]]   #문자열>실수형>정수형 

arr=np.array(list_data)

print(arr)
print(type(arr))

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [34]:
arr1=np.arange(1,10,2)

arr1

array([1, 3, 5, 7, 9])

In [38]:
arr=np.zeros(10, dtype=int)
print(arr)

[0 0 0 0 0 0 0 0 0 0]


In [39]:
arr=np.zeros((2,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [40]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [41]:
int_arr=np.array([1,2,3,4])
print(int_arr)
print(int_arr.ndim)
print(int_arr.shape)

[1 2 3 4]
1
(4,)


In [50]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

arr.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [56]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(type(a),type(b))

a*b

<class 'numpy.ndarray'> <class 'numpy.ndarray'>


array([ 4, 10, 18])

In [58]:
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

answer=[]
for di in data:
    answer.append(2*di)
answer


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [59]:
x=np.array(data)
2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [61]:
#행의 개수 len(c), 열의 개수 len(c[0]), 배열의 깊이 ,len(d[0][0])
a=np.array([0,1,2,3,4])
print(a[2])
print(a[-1])

2
4


In [70]:
a=np.array([[0,1,2],[3,4,5]])
print(a[0,0])
print(a[0,1])
print(a[1,-1])

0
1
5


In [80]:
a=np.array([[0,1,2,3],
            [4,5,6,7]])
print(a[0,1],a[1,1])
print(a[:,1])
print(a[1:,1:])
print(a[:,0:2])

1 5
[1 5]
[[5 6 7]]
[[0 1]
 [4 5]]


In [83]:
a=np.array([1,2,3])
b=np.array([10,20,30])

print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [84]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
 False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [85]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx=np.array(x%2==0)
a[idx]

array([0, 2, 4, 6, 8])

In [86]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [87]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [88]:
print(a[a>4])

[5 6 7 8 9]


In [90]:
#fancy indexing 정수배열인덱싱

a=np.array([11,22,33,44,55,66,77,88,99])
idx=np.array([0,2,4,6,8])       #인덱스 번호가 된다다
a[idx]

array([11, 33, 55, 77, 99])

In [104]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
idx=np.array(a[0,1,2])
a[idx]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [100]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
idx=np.array([2,0,1])       #인덱스 번호가 된다   
a[idx]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

#### 판다스

In [105]:
import pandas

ModuleNotFoundError: No module named 'pandas'

In [106]:
pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ----------------------- ---------------- 6.8/11.5 MB 37.0 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 34.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [107]:
import pandas as pd

In [108]:
pd.__version__

'2.2.3'

In [110]:
s=pd.Series([3,-5,7,4])
print(s)
print(type(s))

0    3
1   -5
2    7
3    4
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
s=pd.Series([3,-5,7,4])
print(s)
print(type(s))

In [112]:
s=pd.Series([3,-5,7,4],index=['a','b','c','d'])
print(s)
print(type(s))

a    3
b   -5
c    7
d    4
dtype: int64
<class 'pandas.core.series.Series'>


In [113]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [114]:
s.values

array([ 3, -5,  7,  4])

In [120]:
df=pd.DataFrame({'Division':['부산광역시','전라남도','강원도'],
                 'Code':['051','061','033'],
                 'Population':[3364358,1840921,1535530]})
print(type(df))
df

<class 'pandas.core.frame.DataFrame'>


Division Code  Population
0    부산광역시  051     3364358
1     전라남도  061     1840921
2      강원도  033     1535530

In [121]:
df.values

array([['부산광역시', '051', 3364358],
       ['전라남도', '061', 1840921],
       ['강원도', '033', 1535530]], dtype=object)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Division    3 non-null      object
 1   Code        3 non-null      object
 2   Population  3 non-null      int64 
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [128]:
df=pd.read_csv('heroes.csv')
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [127]:
pd.options.display.float_format = '{:.0f}'.format

In [129]:
df.info()

#결측치 non null에서 빠짐 토르 원더우먼 거지 Not a number

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [132]:
df.head()

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [130]:
df.tail()

이름  나이     직업     국적    키         재산
2  스파이더맨  18   고등학생     미국  177        600
3   원더우먼  27     공주  데미스키라  178        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
5   캡틴마블  25    파일럿     미국  170  340000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [131]:
df.describe()
#숫자로 처리할 수 있는 값만 꺼내줌. 

나이   키          재산
count   7   7           5
mean   34 190  2578000120
std    13  36  5003440739
min    18 170         600
25%    26 172    50000000
50%    32 177   340000000
75%    39 184  1000000000
max    58 270 11500000000

In [134]:
df['국적'].unique()

array(['미국', '아스가르드', '데미스키라', '러시아'], dtype=object)

In [135]:
df['국적'].value_counts()

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64

In [136]:
df['나이'].nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [137]:
df.nlargest(3,'나이')

이름  나이     직업     국적    키          재산
0  아이언맨  58    CEO     미국  174 11500000000
1    토르  45      신  아스가르드  190         NaN
4    헐크  33  핵물리학자     미국  270  1000000000

In [140]:
df.나이.nlargest()

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

In [142]:
df[['이름','나이']].nlargest(7,'나이')

이름  나이
0   아이언맨  58
1     토르  45
4     헐크  33
6  블랙위도우  32
3   원더우먼  27
5   캡틴마블  25
2  스파이더맨  18

In [144]:
df['이름'][1:6]

1       토르
2    스파이더맨
3     원더우먼
4       헐크
5     캡틴마블
Name: 이름, dtype: object

In [145]:
df[0:2]

이름  나이   직업     국적    키          재산
0  아이언맨  58  CEO     미국  174 11500000000
1    토르  45    신  아스가르드  190         NaN

In [147]:
df.iloc[0]           #데이터프레임명.iloc(행,열) 판다스에서 한줄을 뽑아내면 시리즈즈

이름          아이언맨
나이            58
직업           CEO
국적            미국
키            174
재산   11500000000
Name: 0, dtype: object

In [148]:
df.iloc[[1,3,4]]                  #여러줄 데이터 프레임

이름  나이     직업     국적    키         재산
1    토르  45      신  아스가르드  190        NaN
3  원더우먼  27     공주  데미스키라  178        NaN
4    헐크  33  핵물리학자     미국  270 1000000000

In [149]:
df.iloc[1:4]

이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

In [150]:
df

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [151]:
df.iloc[0,0]

'아이언맨'

In [153]:
df.iloc[:5,:3]

이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자

In [154]:
df2=df.copy()
df2.index=['a','b','c','d','e','f','g']
df2

이름  나이     직업     국적    키          재산
a   아이언맨  58    CEO     미국  174 11500000000
b     토르  45      신  아스가르드  190         NaN
c  스파이더맨  18   고등학생     미국  177         600
d   원더우먼  27     공주  데미스키라  178         NaN
e     헐크  33  핵물리학자     미국  270  1000000000
f   캡틴마블  25    파일럿     미국  170   340000000
g  블랙위도우  32    스파이    러시아  170    50000000

In [157]:
df2.loc['a':'b']             #레이블을 잘라서 오기 때문에 b가 포함됨됨

이름  나이   직업     국적    키          재산
a  아이언맨  58  CEO     미국  174 11500000000
b    토르  45    신  아스가르드  190         NaN

In [162]:
df2.loc['a':'b','이름':'직업']

이름  나이   직업
a  아이언맨  58  CEO
b    토르  45    신

In [164]:
df[df['재산'].isnull()]

이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

In [170]:
df[(df['나이'])>30]

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000
6  블랙위도우  32    스파이    러시아  170    50000000

In [174]:
df[(df['나이']>30)&(df['나이']<50)]

이름  나이     직업     국적    키         재산
1     토르  45      신  아스가르드  190        NaN
4     헐크  33  핵물리학자     미국  270 1000000000
6  블랙위도우  32    스파이    러시아  170   50000000

In [176]:
df.loc[(df['나이'] > 30)&(df['나이']<50), '이름':'직업']

이름  나이     직업
1     토르  45      신
4     헐크  33  핵물리학자
6  블랙위도우  32    스파이

In [177]:
df_a=df.sort_values('키')  #오름차순

이름  나이     직업     국적    키          재산
6  블랙위도우  32    스파이    러시아  170    50000000
5   캡틴마블  25    파일럿     미국  170   340000000
0   아이언맨  58    CEO     미국  174 11500000000
2  스파이더맨  18   고등학생     미국  177         600
3   원더우먼  27     공주  데미스키라  178         NaN
1     토르  45      신  아스가르드  190         NaN
4     헐크  33  핵물리학자     미국  270  1000000000

In [179]:
df.sort_values('재산',ascending=False)  #내림차순순

이름  나이     직업     국적    키          재산
0   아이언맨  58    CEO     미국  174 11500000000
4     헐크  33  핵물리학자     미국  270  1000000000
5   캡틴마블  25    파일럿     미국  170   340000000
6  블랙위도우  32    스파이    러시아  170    50000000
2  스파이더맨  18   고등학생     미국  177         600
1     토르  45      신  아스가르드  190         NaN
3   원더우먼  27     공주  데미스키라  178         NaN

In [181]:
df2['국적']='대한민국'
df2

이름  나이     직업    국적    키          재산
a   아이언맨  58    CEO  대한민국  174 11500000000
b     토르  45      신  대한민국  190         NaN
c  스파이더맨  18   고등학생  대한민국  177         600
d   원더우먼  27     공주  대한민국  178         NaN
e     헐크  33  핵물리학자  대한민국  270  1000000000
f   캡틴마블  25    파일럿  대한민국  170   340000000
g  블랙위도우  32    스파이  대한민국  170    50000000

In [182]:
df2['전투력']=[90,100,46,70,89,78,65]
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   90
b     토르  45      신  대한민국  190         NaN  100
c  스파이더맨  18   고등학생  대한민국  177         600   46
d   원더우먼  27     공주  대한민국  178         NaN   70
e     헐크  33  핵물리학자  대한민국  270  1000000000   89
f   캡틴마블  25    파일럿  대한민국  170   340000000   78
g  블랙위도우  32    스파이  대한민국  170    50000000   65

In [183]:
df2['전투력']=df2['전투력']-5       #df2['전투력'] -= 5 복합대입연산자
df2

이름  나이     직업    국적    키          재산  전투력
a   아이언맨  58    CEO  대한민국  174 11500000000   85
b     토르  45      신  대한민국  190         NaN   95
c  스파이더맨  18   고등학생  대한민국  177         600   41
d   원더우먼  27     공주  대한민국  178         NaN   65
e     헐크  33  핵물리학자  대한민국  270  1000000000   84
f   캡틴마블  25    파일럿  대한민국  170   340000000   73
g  블랙위도우  32    스파이  대한민국  170    50000000   60

In [188]:
df2.columns=['성명','연령','하는일','출신국가','신장','재산현황','파워']
df2

성명  연령    하는일  출신국가   신장        재산현황  파워
a   아이언맨  58    CEO  대한민국  174 11500000000  85
b     토르  45      신  대한민국  190         NaN  95
c  스파이더맨  18   고등학생  대한민국  177         600  41
d   원더우먼  27     공주  대한민국  178         NaN  65
e     헐크  33  핵물리학자  대한민국  270  1000000000  84
f   캡틴마블  25    파일럿  대한민국  170   340000000  73
g  블랙위도우  32    스파이  대한민국  170    50000000  60

In [ ]:
df2.drop(index=['a'],inplace=True)  #행을 삭제할 땐 인덱스스

In [191]:
df2

성명  연령    하는일  출신국가   신장       재산현황  파워
b     토르  45      신  대한민국  190        NaN  95
c  스파이더맨  18   고등학생  대한민국  177        600  41
d   원더우먼  27     공주  대한민국  178        NaN  65
e     헐크  33  핵물리학자  대한민국  270 1000000000  84
f   캡틴마블  25    파일럿  대한민국  170  340000000  73
g  블랙위도우  32    스파이  대한민국  170   50000000  60

In [192]:
df2.drop(columns=['파워'],inplace=True)  #컬럼 삭제

In [193]:
df2

성명  연령    하는일  출신국가   신장       재산현황
b     토르  45      신  대한민국  190        NaN
c  스파이더맨  18   고등학생  대한민국  177        600
d   원더우먼  27     공주  대한민국  178        NaN
e     헐크  33  핵물리학자  대한민국  270 1000000000
f   캡틴마블  25    파일럿  대한민국  170  340000000
g  블랙위도우  32    스파이  대한민국  170   50000000

In [ ]:
df2.dropna()   ## 기본 axis인 행단위로 삭제됨

In [ ]:
df2.dropna(axis=1)  #null이 있는 컬럼 자체가 삭제됨

In [196]:
df2.fillna(method='bfill')

C:\Users\USER\AppData\Local\Temp\ipykernel_9776\2667140817.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2.fillna(method='bfill')


성명  연령    하는일  출신국가   신장       재산현황
b     토르  45      신  대한민국  190        600
c  스파이더맨  18   고등학생  대한민국  177        600
d   원더우먼  27     공주  대한민국  178 1000000000
e     헐크  33  핵물리학자  대한민국  270 1000000000
f   캡틴마블  25    파일럿  대한민국  170  340000000
g  블랙위도우  32    스파이  대한민국  170   50000000

In [199]:
df2['재산현황'].mean()

np.float64(347500150.0)